test_that(".count_tweets", {
    expect_equal(einfach:::.count_tweets("../testdata/ica21/"), 11108)
    newdir <- einfach:::.gen_random_dir()
    expect_equal(einfach:::.count_tweets(newdir), 0)
    fs::dir_create(newdir)
    expect_equal(einfach:::.count_tweets(newdir), 0)
    x <- c("rubbish")
    writeLines(x, tempfile(tmpdir = newdir))
    expect_true(length(fs::dir_ls(newdir)) == 1)
    expect_equal(einfach:::.count_tweets(newdir), 0)
    unlink(newdir, recursive = TRUE)
})

test_that(".lazy_bind_tweets", {
    set.seed(46709394)
    test_df <- einfach:::.lazy_bind_tweets("../testdata/ica21/")
    expect_lt(nrow(test_df), 11108)
    expect_lt(nrow(test_df), 1000)
    expect_lt(nrow(test_df), 1000)    
    expect_gt(nrow(test_df), 100)
    expect_true("tbl_df" %in% class(test_df))
    newdir <- einfach:::.gen_random_dir()
    test_df2 <- einfach:::.lazy_bind_tweets(newdir)
    expect_equal(nrow(test_df2), 0)
    expect_true("tbl_df" %in% class(test_df2))
    fs::dir_create(newdir)
    test_df3 <- einfach:::.lazy_bind_tweets(newdir)
    expect_equal(nrow(test_df3), 0)
    expect_true("tbl_df" %in% class(test_df3))
    x <- c("rubbish")
    writeLines(x, tempfile(tmpdir = newdir))
    expect_true(length(fs::dir_ls(newdir)) == 1)
    test_df3 <- einfach:::.lazy_bind_tweets(newdir)
    expect_equal(nrow(test_df3), 0)
    expect_true("tbl_df" %in% class(test_df3))
    unlink(newdir, recursive = TRUE)    
})
